from controller.AuthController import AuthController
from controller.VoteController import VoteController
from controller.RecordVoteController import RecordVoteController
from controller.RegisterController import RegisterController
from controller.StatsController import StatsController
from controller.ReportController import ReportController